### ISSUE TITLE
Reflex 0.5.0 Roadmap

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#2727]
NOTE: We recently released Reflex 0.4.0 with new core components and a theming system - see the [blog post](https://reflex.dev/blog/2024-02-16-reflex-v0.4.0) for more info and for a guide on upgrading existing projects.

--- 

This page is a living document outlining the major projects we're working on next for reflex 0.5.0. The projects are ordered more-or-less in the order we plan to complete them.

Feel free to comment to leave feedback or upvote any issues you'd like to see prioritized, and we welcome outside contributions for any issues.

## Themes for 0.5.0

**Stability**: As we approach our 1.0 release, we're focused on making our core API stable and limiting breaking changes so Reflex can be a solid foundation for long-term projects.

**Simplicity**: We want to improve the out of the box experience so users can focus on their ideas rather than implementation. This includes building a 3rd party component ecosystem, as well as simplifying the APIs for many of our core components. 

**Speed**: Reflex apps should be fast, both for the end user and for the developer. We have projects to make sure apps stay fast as they grow in size, and to improve the compile / hot-reload times so devs can iterate quickly when building.

### Performance
- [ ] State Sharding
- [ ] Pydantic 2.0 Migration / Removal
- [ ] Benchmarking Suite
- [ ] Remove Middleware
- [ ] Compile Performance Checks
- [ ] Immutable Components
- [ ] Factor Out State Manager / Dependencies

### Usability
- [ ] 3rd Party Component Ecosystem https://github.com/reflex-dev/reflex/issues/2706
- [ ] Substate Access
- [ ] High Level API for Core Components
- [ ] Consistent Theming
- [ ] Graphing Improvements
- [ ] DataTable / DataEditor Improvements
- [ ] Decentralized Var Operations
- [ ] Simplify Component Type Annotations
- [ ] Responsive Support For All Props
- [ ] Decentralized Var Operations

**Comment by abulvenz** [comment]
Firstly, I :heart:  like the plans and think the three main goals are a good focusing point for 0.5.0.
One minor drop of bitterness (at least for my current code):
Remove the middleware :scream_cat: ? I would need new ideas for authorization then. I do not want to rely entirely on the routing and if-statements. What are the ideas how authorization (I don't mean solely authentication here) might be added to an app?
Other things that middleware is good for: Checking when the last action of a user had been carried out. Conditionally having fine-grained influence on states. Debugging event orders by mere printing. 
Maybe there are plans to have a similar mechanism that replaces this nice (not tremendously over-documented ;) feature?

**Comment by benedikt-bartscher** [comment]
Awesome, love to see how reflex evolves! :rocket: 
Is Pydantic v2 fixed on this roadmap? If so, I would offer my help regarding SQLAlchemy support and adjust my affected PRs to pydantic v2.

**Comment by picklelo** [comment]
@abulvenz Thanks for the feedback - I will modify that project, we don't want to break any existing functionality. 

We want to move certain internal events like the initial state hydration away from using middleware, but we will still have easy ways to support other use cases.

**Comment by picklelo** [comment]
@benedikt-bartscher Yes we either want to upgrade to Pydantic v2.0 for the performance and compatibility benefits

In the long-term we can potentially remove the Pydantic dependency altogether and use Python dataclasses, since we don't use many of its features anymore internally. Though that would require moving away from FastAPI and SQLModel, so not planned anytime soon.

**Comment by cllatser** [comment]
Hi everyone, as I have said before. I have been programming for a short time, I did a Python Bootcamp and for the final project I used Reflex when it was called Pynecone. I could have used Django or Flask, but I chose Reflex because I think it will have a future.

What would I like from Reflex 1.0?

Let's see if I can explain. I would like Reflex to be from a base agnostic of any external framework, using as it can be done now 100% html and css. So as not to depend on third party libraries, such as Astro (Javascript).

From there, when starting the project the user will be asked whether or not to use a framework or not, for example Radix-Ui, Taildwind.

Then the ability to share components with (3rd Party Component Ecosystem) seems to me great.

Good job to all the team, long life to Reflex.

Best regards.

**Comment by dentroai** [comment]
Perhaps these thoughts help you in finding the right direction for your product.

Started to use reflex because:
- wanted same coding language as most ML frameworks -> python
- wanted a low code tool that's flexible. Using little code to achieve common use cases with the possibility to customize easily
- wanted frontend and backend in one, allowing for a single code base that can handle auth and user management
- used streamlit before, but can't build any serious project with it because customizing look of components is a pain, page randomly refreshes deleting existing state, weird logic where the code is rendered top to bottom making common use cases difficult to implement (or at least much different)
- need to be able to self-host it for GDPR critical use cases

Like it even more since I started:
- wrappers of 3rd party libraries like motion
- askInkeep on discord
- team on discord is very responsive
- hosted version for non GDPR criticial use cases
- lots of inbuilt components that actually do work out of the box such as file upload or scrollable area

**Comment by include** [comment]
Really like to see the "Simplicity" point here. box system is really a pita :) - thank you for Reflex!

**Comment by Sprocketer** [comment]
> @benedikt-bartscher Yes we either want to upgrade to Pydantic v2.0 for the performance and compatibility benefits
> 
> In the long-term we can potentially remove the Pydantic dependency altogether and use Python dataclasses, since we don't use many of its features anymore internally. Though that would require moving away from FastAPI and SQLModel, so not planned anytime soon.

@picklelo In terms of improving performance - I'm not sure how much Javascript next.js (which seems to be under the hood) uses, but have you seen Astro? Seems to be super fast because it renders static JS components as HTML. Might be a reach, but maybe there's some way to include something similar at build-time?

**Comment by ibehnam** [comment]
Thanks @picklelo, the roadmap looks awesome! I just wanted to chime in as someone who's used Streamlit in the past and has suffered from its limitations. I believe what makes Streamlit popular among the ML community is the new "AI" features they added, like the ability to build a chat UI which looks nice. I saw the chat UI demo using Reflex and I thought it would be much better if more time was spent on that. It surely would attract people who want to build fancy chat UIs. Currently, Streamlit does it in a way that's not performant but looks nice, so the higher-ups often like it. If there was some theming for chat UI, messages, etc., I think it would help Reflex a lot. Just a thought!

**Comment by pnsvk** [comment]
Possibilities of building a desktop version of reflex would be a game changer.. something on the lines of [stlite](https://github.com/whitphx/stlite).
I am thinking of trying out [Briefcase](https://beeware.org/briefcase/), but not getting time.. Sure things may not be as straight forward, as Briefcase is all native-desktop friendly.

Atleast, perhaps an effective blog post detailing a success-story around this would definitely help the community.. Please kindly consider.

**Comment by pnsvk** [comment]
The initial boot-up of the app and hot-reload are both very time-consuming.. Sorry to keep comparing with Streamlit, but the hot-reload is almost instantaneous with it. I am finding it painful to maintain a growing streamlit app, and seeing value with migrating to Reflex, hence the ask/request/plead..

**Comment by ibehnam** [comment]
@pnsvk Okay, stick to Streamlit then. Changes in Streamlit are instantaneous because Streamlit doesn't compile (unlike Reflex which compiles to performant HTML+CSS+JS code). Streamlit was based on poor design decisions (e.g., every interaction with any widget reloads the entire page, wtf?). Recently, they've tried to fix some of them (e.g., local reloading) but the overall project is still a mess.

**Comment by pnsvk** [comment]
> @pnsvk Okay, stick to Streamlit then. Changes in Streamlit are instantaneous because Streamlit doesn't compile (unlike Reflex which compiles to performant HTML+CSS+JS code). Streamlit was based on poor design decisions (e.g., every interaction with any widget reloads the entire page, wtf?). Recently, they've tried to fix some of them (e.g., local reloading) but the overall project is still a mess.

"stick to Streamlit then"? Wow.. How polite.. :-)
But still, thank you for the explanation.. Thought I would provide an end-developer experience with the framework..

**Comment by Lendemor** [comment]
Small bump for anyone following this issue, 0.7.0 roadmap is available, let us know your thoughts.

**Comment by TimChild** [comment]
Are there any plans to fully move to pydantic v2? I.e. having `rx.Base` subclass the v2 pydantic `BaseModel` instead of v1? 

It seems like most packages at this point have made the transition fully to v2 and I'd really like to be able to stop thinking about v1 for good.

Before `0.6.0` I was somehow getting away with using v2 models as state attributes, but I've just tried upgrading from `reflex==0.5.9` to `0.6.1` and it seems that whatever I had done no longer works. (I'm actually surprised I ever got away with it since v2 and v1 really don't play nice together...).

**Comment by ruben-vanwyk** [comment]
How dependent is the framework internally on FastAPI and wouldn't using something like Litestar offer better performance and allow potentially better full-stack experience in the long-run? Certain things on the roadmap like built-in auth is also included in Litestar. Might be worth taking a look.

**Comment by picklelo** [comment]
@ruben-vanwyk We're not very coupled on FastAPI (we currently mainly use them for their Upload API, as well as exposing backend API routes) - in the future we plan to make that part of Reflex modular so people can use their own backend frameworks if they want.

**Comment by benedikt-bartscher** [comment]
> Are there any plans to fully move to pydantic v2? I.e. having `rx.Base` subclass the v2 pydantic `BaseModel` instead of v1?

Is this still planned? Or do you want to migrate `rx.Base` to dataclasses instead?

**Comment by laike9m** [comment]
Maybe this is mentioned somewhere: **is there a tentative timeline for when 0.7 will come out (and perhaps 1.0 too)**?

I mostly care about the built-in auth feature.

**Comment by TimChild** [comment]
> > Are there any plans to fully move to pydantic v2? I.e. having `rx.Base` subclass the v2 pydantic `BaseModel` instead of v1?
> 
> Is this still planned? Or do you want to migrate `rx.Base` to dataclasses instead?

On the thread of reflex and pydantic...

The recent [v0.6.6 release](https://github.com/reflex-dev/reflex/releases/tag/v0.6.6) adds support for v2 models to be used as state vars which is very nice.

**Comment by bilgilendir** [comment]
It would be helpful if you could also include a fix for this [bug](https://github.com/reflex-dev/reflex/issues/4376) https://github.com/reflex-dev/reflex/issues/4376

**Comment by itsmeadarsh2008** [comment]
Add #4694 ?

**Comment by Seikened** [comment]
I noticed that the current roadmap focuses on version 0.7.0, but we’re already at 0.7.1. Could you please confirm whether the roadmap is still current or if new priorities and plans have emerged for upcoming versions? @picklelo

**Comment by picklelo** [comment]
@Seikened I just updated the roadmap for our current goals!

For the open source our core focus is on making things faster and more stable while encouraging custom components to move to third party packages to keep reflex more modular. If there are any features people want us to prioritize in the core, let us know in the thread.

**Comment by bertbarabas** [comment]
Is there still going to be a base AG Grid widget available and maintained for the free Reflex tier? I know AG Grid itself has a base and enterprise version so I was wondering if the base version of ag grid would remain available in the free tier and perhaps the enterprise version features of ag grid would be in the enterprise tier of Reflex. Or is everything ag grid related that will be maintained going forward only for the enterprise reflex tier?

**Comment by Lendemor** [comment]
> Is there still going to be a base AG Grid widget available and maintained for the free Reflex tier? I know AG Grid itself has a base and enterprise version so I was wondering if the base version of ag grid would remain available in the free tier and perhaps the enterprise version features of ag grid would be in the enterprise tier of Reflex. Or is everything ag grid related that will be maintained going forward only for the enterprise reflex tier?

The version of AG Grid we will maintain will be in the enterprise package.
That package can be used by free tier, but the Reflex badge will be showing in all pages.

Of course, anyone is free to make their own wrap of AG Grid if they don't want either the badge or the team plan.

**Comment by SomniaUmbra** [comment]
Any ETA on when tailwind v4 upgrade would be available?

**Comment by Droxvor** [comment]
Hi

**Comment by Lendemor** [comment]
> Any ETA on when tailwind v4 upgrade would be available?

This is available starting from [0.7.13](https://github.com/reflex-dev/reflex/releases/tag/v0.7.13).

Both v3 and v4 are useable, you can change which one you want by settings `plugins=[...]` in rxconfig.py

There might be more work needed for v4 to be considered stable, so let us know if you have any feedback.

**Comment by SomniaUmbra** [comment]
I am getting Module is not callable error.

```py
import reflex as rx

config = rx.Config(
    app_name="landing",
    telemetry_enabled=False,
    show_built_with_reflex=False,
    plugins = [
        rx.plugins.tailwind_v4()
    ]
)
```

**Comment by Lendemor** [comment]
> I am getting Module is not callable error.
> 
> ```py
> import reflex as rx
> 
> config = rx.Config(
>     app_name="landing",
>     telemetry_enabled=False,
>     show_built_with_reflex=False,
>     plugins = [
>         rx.plugins.tailwind_v4()
>     ]
> )
> ```

Make sure to use the exact syntax suggested by the warning when setting your config.

**Comment by SomniaUmbra** [comment]
> exact syntax suggested by the warning


```

  File "/home/v/Projects/Python/reflex/404-personality-not-found/rxconfig.py", line 24, in <module>
    rx.plugins.tailwind_v4()
    ~~~~~~~~~~~~~~~~~~~~~~^^
TypeError: 'module' object is not callable
```

~~It doesn't tell me anything except this. In reflex's release the supposed module is `TailwindV4Plugin()`, but it's not a thing in the reality, it's is `tailwind_v4()`.~~

~~btw it's the case for both v3 and v4 plugins.~~

nevermind, it works now, I don't know why it wasn't working previously. Neither does it show up in autocomp

**Comment by SomniaUmbra** [comment]
I don't suppose the newer tailwindv4 plugin supports installing plugin?

```py
# landing/landing.py

import reflex as rx

app = rx.App(
    stylesheets=["/daisy_styles.css"],
)
```

```css
/* daisy_styles.css */

@import "tailwindcss";
@plugin "daisyui";
```

This does not install daisy.

**Comment by NormanShelley** [comment]
> [@benedikt-bartscher](https://github.com/benedikt-bartscher) Yes we either want to upgrade to Pydantic v2.0 for the performance and compatibility benefits
> 
> In the long-term we can potentially remove the Pydantic dependency altogether and use Python dataclasses, since we don't use many of its features anymore internally. Though that would require moving away from FastAPI and SQLModel, so not planned anytime soon.

You might consider looking in **msgspec** instead of **dataclasses**. https://jcristharif.com/[msgspec](https://jcristharif.com/msgspec/

**Comment by HasanRad021** [comment]
👌👌👌

**Comment by CMajorChords** [comment]
Making the Reflex MCP open-source as a standalone tool—or offering it for individual subscription—would solidify Reflex’s dominance in the Python web ecosystem. This move would significantly expand the training corpus for the latest Reflex APIs, making AI-assisted development even more powerful.

**Comment by larsblumberg** [comment]
What's your take on adding offline support, e.g. deploying the backend (as WASL) together with the frontend so that Reflex survive connectivity issues. Audi likely reduces some performance issues for when lots of state is exchanged.

**Comment by masenf** [comment]
@larsblumberg in the process of updating the roadmap currently. I want to see better offline support, I think we're going to implement the core with replicache (or similar) which should give some offline ability while largely being backend driven.

No immediate plans to have reflex running in the browser though.
